name: Reuse other workflow

on: [workflow_dispatch]

jobs:
  call-workflow:
    runs-on: ubuntu-latest
    strategy: 
      matrix: 
        greet-params: ['@I-Monev', 'someone else']
    steps:
      - uses: ./.github/workflows/reusable.yml
        with: 
          who-to-greet: ${{matrix.greet-params}}
      
  use-output:
    runs-on: ubuntu-latest
    needs: [call-workflow]
    steps:
      - run: echo "Time was ${{ needs.call-workflow.outputs.current-time }}"
